//! Pixel operations checked against Pillow's own output.
//!
//! The fixtures in `tests/fixtures/` were generated by running Pillow directly
//! (see `PORTING.md`). They exist so the reproductions of `convert("L")`,
//! `ImageOps.autocontrast` and `ImageEnhance.Contrast` cannot drift without a
//! test noticing.

use std::collections::BTreeSet;

use epubkit_core::image::{
    adjust_contrast, autocontrast, device, floyd_steinberg, luma_601, process_image, to_gray_601,
    ImageOptions, MAX_IMAGE_DIMENSION, SSD1677_LEVELS, X3, X4,
};
use image::{DynamicImage, GrayImage, ImageFormat, Luma, Rgb, RgbImage};

fn fixture(name: &str) -> String {
    std::fs::read_to_string(format!(
        "{}/tests/fixtures/{name}",
        env!("CARGO_MANIFEST_DIR")
    ))
    .unwrap_or_else(|e| panic!("missing fixture {name}: {e}"))
}

/// Read a two-line fixture: input values, then Pillow's expected output.
fn pixel_fixture(name: &str) -> (Vec<u8>, Vec<u8>) {
    let text = fixture(name);
    let mut lines = text.lines();
    let parse = |line: &str| -> Vec<u8> {
        line.split_whitespace()
            .map(|v| v.parse().expect("fixture value"))
            .collect()
    };
    let input = parse(lines.next().expect("input line"));
    let expected = parse(lines.next().expect("expected line"));
    assert_eq!(input.len(), expected.len());
    (input, expected)
}

fn row(values: &[u8]) -> GrayImage {
    GrayImage::from_raw(values.len() as u32, 1, values.to_vec()).expect("row image")
}

#[test]
fn grayscale_matches_pillow() {
    let mut checked = 0;
    for line in fixture("luma601.txt").lines() {
        let v: Vec<u32> = line
            .split_whitespace()
            .map(|n| n.parse().unwrap())
            .collect();
        let (r, g, b, expected) = (v[0] as u8, v[1] as u8, v[2] as u8, v[3] as u8);
        assert_eq!(
            luma_601(r, g, b),
            expected,
            "luma_601({r},{g},{b}) disagrees with Pillow"
        );
        checked += 1;
    }
    assert!(checked > 1000, "fixture looks truncated: {checked} samples");
}

/// The whole reason for writing the coefficients out by hand: the Rec. 709
/// values most crates default to give visibly different greys.
#[test]
fn grayscale_is_not_rec_709() {
    // Pure green is where the two standards disagree most.
    assert_eq!(luma_601(0, 255, 0), 150);
    let rec709 = (255u32 * 7152 / 10000) as u8;
    assert_ne!(luma_601(0, 255, 0), rec709);
}

#[test]
fn autocontrast_matches_pillow() {
    for name in [
        "autocontrast_full.txt",
        "autocontrast_narrow.txt",
        "autocontrast_dark.txt",
        "autocontrast_flat.txt",
    ] {
        let (input, expected) = pixel_fixture(name);
        let mut gray = row(&input);
        autocontrast(&mut gray, 1);
        assert_eq!(gray.into_raw(), expected, "{name} disagrees with Pillow");
    }
}

#[test]
fn contrast_matches_pillow() {
    for (name, factor) in [
        ("contrast_15.txt", 1.5),
        ("contrast_20.txt", 2.0),
        ("contrast_05.txt", 0.5),
    ] {
        let (input, expected) = pixel_fixture(name);
        let mut gray = row(&input);
        adjust_contrast(&mut gray, factor);
        assert_eq!(gray.into_raw(), expected, "{name} disagrees with Pillow");
    }
}

/// Contrast pivots about the image's own mean, not mid-grey. On a dark image
/// the two give very different answers, and getting it wrong would blow out
/// every night scene in every book.
#[test]
fn contrast_pivots_on_the_image_mean() {
    let dark = vec![40u8; 100];
    let mut gray = row(&dark);
    adjust_contrast(&mut gray, 2.0);

    // Mean is 40, so every pixel is already at the pivot and cannot move.
    assert!(
        gray.pixels().all(|p| p[0] == 40),
        "a flat image should be unchanged by a contrast adjustment"
    );

    // Pivoting on 128 would have pushed these to 0.
    let naive = (128.0 + 2.0 * (40.0 - 128.0)) as i32;
    assert!(naive < 0, "sanity: the naive pivot would clamp to black");
}

#[test]
fn dithering_emits_only_device_levels() {
    // A smooth ramp is the hardest case: every intermediate value has to be
    // expressed as a mix of the four available ones.
    let ramp: Vec<u8> = (0..=255u8).collect();
    let mut gray = GrayImage::from_raw(16, 16, ramp).unwrap();

    floyd_steinberg(&mut gray, SSD1677_LEVELS);

    let seen: BTreeSet<u8> = gray.pixels().map(|p| p[0]).collect();
    let allowed: BTreeSet<u8> = SSD1677_LEVELS.iter().copied().collect();
    assert!(
        seen.is_subset(&allowed),
        "output contains values outside the palette: {seen:?}"
    );
}

/// Error diffusion's defining property: it trades spatial accuracy for tonal
/// accuracy, so the average brightness of a region survives quantization.
#[test]
fn dithering_preserves_average_brightness() {
    for level in [30u8, 64, 100, 128, 190, 220] {
        let mut gray = GrayImage::from_pixel(64, 64, Luma([level]));
        floyd_steinberg(&mut gray, SSD1677_LEVELS);

        let mean: f64 =
            gray.pixels().map(|p| p[0] as f64).sum::<f64>() / gray.pixels().len() as f64;
        assert!(
            (mean - level as f64).abs() < 6.0,
            "flat {level} dithered to mean {mean:.1}, too far off"
        );
    }
}

/// A mid-tone that is not itself a palette level has to be rendered as a mix,
/// not snapped to the nearest level across the whole region.
#[test]
fn dithering_actually_diffuses() {
    let mut gray = GrayImage::from_pixel(32, 32, Luma([128]));
    floyd_steinberg(&mut gray, SSD1677_LEVELS);

    let seen: BTreeSet<u8> = gray.pixels().map(|p| p[0]).collect();
    assert!(
        seen.len() >= 2,
        "a flat mid-tone should dither to a mix, got {seen:?}"
    );
}

#[test]
fn dithering_a_flat_palette_value_is_a_no_op() {
    for &level in SSD1677_LEVELS {
        let mut gray = GrayImage::from_pixel(8, 8, Luma([level]));
        floyd_steinberg(&mut gray, SSD1677_LEVELS);
        assert!(
            gray.pixels().all(|p| p[0] == level),
            "level {level} should survive untouched"
        );
    }
}

// ------------------------------------------------------------ whole pipeline

fn photo(width: u32, height: u32) -> Vec<u8> {
    // A gradient with a hard edge: exercises both smooth tone and detail.
    let mut rgb = RgbImage::new(width, height);
    for (x, y, pixel) in rgb.enumerate_pixels_mut() {
        let ramp = ((x * 255) / width.max(1)) as u8;
        let band = if (y / 8) % 2 == 0 { 40 } else { 0 };
        *pixel = Rgb([ramp.saturating_add(band), ramp, 255 - ramp]);
    }

    let mut out = Vec::new();
    DynamicImage::ImageRgb8(rgb)
        .write_to(&mut std::io::Cursor::new(&mut out), image::ImageFormat::Png)
        .unwrap();
    out
}

fn decode(bytes: &[u8]) -> DynamicImage {
    image::load_from_memory(bytes).expect("output should decode")
}

#[test]
fn processing_fits_the_device_box() {
    let source = photo(1600, 2400);
    let results = process_image(&source, "plate.png", &ImageOptions::for_device(X4)).unwrap();

    assert_eq!(results.len(), 1);
    let out = decode(&results[0].bytes);
    assert!(out.width() <= X4.width, "width {} > 480", out.width());
    assert!(out.height() <= X4.height, "height {} > 800", out.height());
    assert_eq!(results[0].filename, "plate.jpg");
}

#[test]
fn the_x3_profile_uses_its_own_box() {
    let source = photo(1600, 2400);
    let results = process_image(&source, "plate.png", &ImageOptions::for_device(X3)).unwrap();
    let out = decode(&results[0].bytes);

    assert!(out.width() <= X3.width);
    assert!(out.height() <= X3.height);
    assert_eq!(device("x3").unwrap().width, 528);
}

#[test]
fn small_images_are_never_enlarged() {
    let source = photo(100, 120);
    let results = process_image(&source, "small.png", &ImageOptions::default()).unwrap();
    let out = decode(&results[0].bytes);

    assert_eq!((out.width(), out.height()), (100, 120));
}

/// The Xteink spec caps images at 1024 in either direction, regardless of the
/// panel's own size.
#[test]
fn the_hard_dimension_ceiling_is_enforced() {
    let source = photo(4000, 200);
    let options = ImageOptions {
        max_width: 100_000,
        max_height: 100_000,
        ..ImageOptions::default()
    };

    let out = decode(&process_image(&source, "wide.png", &options).unwrap()[0].bytes);
    assert!(out.width() <= MAX_IMAGE_DIMENSION);
    assert!(out.height() <= MAX_IMAGE_DIMENSION);
}

#[test]
fn output_is_baseline_jpeg() {
    let source = photo(400, 600);
    let results = process_image(&source, "plate.png", &ImageOptions::default()).unwrap();
    let bytes = &results[0].bytes;

    assert_eq!(&bytes[0..2], &[0xFF, 0xD8], "not a JPEG");
    // SOF2 marks a progressive frame, which many e-ink readers cannot decode.
    assert!(
        !bytes.windows(2).any(|w| w == [0xFF, 0xC2]),
        "progressive JPEG emitted"
    );
    assert!(
        bytes.windows(2).any(|w| w == [0xFF, 0xC0]),
        "no baseline frame header found"
    );
}

/// Tone survives the whole pipeline. Quantizing to four levels and then
/// encoding to a lossy format should still leave a flat grey reading as that
/// grey overall — which is the property error diffusion exists to provide.
#[test]
fn overall_brightness_survives_the_pipeline() {
    for level in [64u8, 128, 190] {
        let mut rgb = RgbImage::new(128, 128);
        for pixel in rgb.pixels_mut() {
            *pixel = Rgb([level, level, level]);
        }
        let mut source = Vec::new();
        DynamicImage::ImageRgb8(rgb)
            .write_to(
                &mut std::io::Cursor::new(&mut source),
                image::ImageFormat::Png,
            )
            .unwrap();

        let out =
            decode(&process_image(&source, "flat.png", &ImageOptions::default()).unwrap()[0].bytes)
                .to_luma8();
        let mean: f64 = out.pixels().map(|p| p[0] as f64).sum::<f64>() / out.pixels().len() as f64;

        assert!(
            (mean - level as f64).abs() < 8.0,
            "flat {level} came out of the pipeline at {mean:.1}"
        );
    }
}

/// A solid white image must come back solid white. This is the regression
/// guard for the encoder settings, and it earned its keep: it caught
/// `jpeg-encoder`'s optimized-table mode splitting the interleaved scan into
/// three single-component scans, which is legal baseline JPEG but which
/// several decoders — this crate's included — turn into noise. Optimized
/// tables now come from rewriting the finished file instead, which leaves the
/// scan structure alone. See `core::jpeg`.
#[test]
fn a_solid_image_round_trips_through_our_own_decoder() {
    let mut rgb = RgbImage::new(96, 96);
    for pixel in rgb.pixels_mut() {
        *pixel = Rgb([255, 255, 255]);
    }
    let mut source = Vec::new();
    DynamicImage::ImageRgb8(rgb)
        .write_to(
            &mut std::io::Cursor::new(&mut source),
            image::ImageFormat::Png,
        )
        .unwrap();

    let options = ImageOptions {
        contrast_boost: false,
        ..ImageOptions::default()
    };
    let out = decode(&process_image(&source, "white.png", &options).unwrap()[0].bytes).to_luma8();

    let min = out.pixels().map(|p| p[0]).min().unwrap();
    assert!(min > 240, "solid white decoded with pixels down to {min}");
}

#[test]
fn transparency_is_flattened_onto_white() {
    let mut rgba = image::RgbaImage::new(40, 40);
    for pixel in rgba.pixels_mut() {
        *pixel = image::Rgba([0, 0, 0, 0]); // fully transparent black
    }
    let mut source = Vec::new();
    DynamicImage::ImageRgba8(rgba)
        .write_to(
            &mut std::io::Cursor::new(&mut source),
            image::ImageFormat::Png,
        )
        .unwrap();

    let options = ImageOptions {
        contrast_boost: false,
        ..ImageOptions::default()
    };
    let out = decode(&process_image(&source, "clear.png", &options).unwrap()[0].bytes).to_luma8();

    let mean: f64 = out.pixels().map(|p| p[0] as f64).sum::<f64>() / out.pixels().len() as f64;
    assert!(
        mean > 200.0,
        "transparent pixels should have flattened to white, mean was {mean:.1}"
    );
}

#[test]
fn light_novel_mode_splits_a_double_page_spread() {
    let source = photo(2000, 800); // aspect 2.5, well past the spread threshold
    let options = ImageOptions {
        light_novel_mode: true,
        ..ImageOptions::default()
    };

    let results = process_image(&source, "spread.png", &options).unwrap();

    assert_eq!(results.len(), 2, "a spread should become two pages");
    assert_eq!(results[0].filename, "spread_part1.jpg");
    assert_eq!(results[1].filename, "spread_part2.jpg");
    // Only the first result carries the source size, so a report cannot count
    // the same input twice.
    assert!(results[0].original_size > 0);
    assert_eq!(results[1].original_size, 0);
}

#[test]
fn light_novel_mode_rotates_a_single_landscape_image() {
    let source = photo(800, 600); // aspect 1.33, below the spread threshold
    let options = ImageOptions {
        light_novel_mode: true,
        ..ImageOptions::default()
    };

    let results = process_image(&source, "plate.png", &options).unwrap();
    assert_eq!(results.len(), 1);

    let out = decode(&results[0].bytes);
    assert!(
        out.height() > out.width(),
        "a rotated landscape image should end up portrait, got {}x{}",
        out.width(),
        out.height()
    );
}

#[test]
fn light_novel_mode_leaves_portrait_images_alone() {
    let source = photo(600, 900);
    let options = ImageOptions {
        light_novel_mode: true,
        ..ImageOptions::default()
    };

    let results = process_image(&source, "portrait.png", &options).unwrap();
    assert_eq!(results.len(), 1);
    assert_eq!(results[0].filename, "portrait.jpg");
}

#[test]
fn every_output_is_renamed_to_jpg() {
    for name in ["a.png", "b.GIF", "c.webp", "d.bmp", "e.jpeg"] {
        let source = photo(60, 80);
        let results = process_image(&source, name, &ImageOptions::default()).unwrap();
        assert!(
            results[0].filename.ends_with(".jpg"),
            "{name} produced {}",
            results[0].filename
        );
    }
}

/// An image is named and counted by what it is, whatever its file is
/// called: one with no extension, or another than its format's, comes out a
/// `.jpg` of its name, its format read from its bytes.
#[test]
fn an_image_is_converted_by_what_it_is_not_its_name() {
    let png = photo(60, 80);
    let mut jpeg = Vec::new();
    image::load_from_memory(&png)
        .unwrap()
        .write_to(&mut std::io::Cursor::new(&mut jpeg), ImageFormat::Jpeg)
        .unwrap();

    for (name, bytes, filename, conversion) in [
        ("spread", &png, "spread.jpg", "PNG→JPEG"),
        ("plate.bin", &png, "plate.jpg", "PNG→JPEG"),
        ("misnamed.JPG", &png, "misnamed.jpg", "PNG→JPEG"),
        ("photo.jpe", &jpeg, "photo.jpg", "baseline JPEG"),
        ("scan.jfif", &jpeg, "scan.jpg", "baseline JPEG"),
        ("e.TIF", &tiff(&png), "e.jpg", "TIFF→JPEG"),
    ] {
        let results = process_image(bytes, name, &ImageOptions::default()).unwrap();
        assert_eq!(results[0].filename, filename, "{name}");
        assert_eq!(results[0].conversion, conversion, "{name}");
    }
}

/// `png` written again as a TIFF.
fn tiff(png: &[u8]) -> Vec<u8> {
    let mut out = Vec::new();
    image::load_from_memory(png)
        .unwrap()
        .write_to(&mut std::io::Cursor::new(&mut out), ImageFormat::Tiff)
        .unwrap();
    out
}

#[test]
fn corrupt_input_is_reported_not_panicked_on() {
    let garbage = b"this is not an image at all";
    assert!(process_image(garbage, "broken.png", &ImageOptions::default()).is_err());
}

#[test]
fn grayscale_can_be_turned_off() {
    let source = photo(200, 300);
    let options = ImageOptions {
        grayscale: false,
        eink_quantize: false,
        contrast_boost: false,
        ..ImageOptions::default()
    };

    let out = decode(&process_image(&source, "colour.png", &options).unwrap()[0].bytes).to_rgb8();
    let has_colour = out.pixels().any(|p| p[0] != p[1] || p[1] != p[2]);
    assert!(has_colour, "colour should have survived with grayscale off");
}

#[test]
fn details_describe_what_happened() {
    let source = photo(1600, 2400);
    let results = process_image(&source, "plate.png", &ImageOptions::default()).unwrap();
    let details = &results[0].details;

    assert!(details.contains("PNG→JPEG"), "{details}");
    assert!(details.contains("resized"), "{details}");
    assert!(details.contains("4-level grayscale"), "{details}");
    assert!(details.contains("contrast 1.5x"), "{details}");
}

#[test]
fn gray_conversion_goes_through_601() {
    let mut rgb = RgbImage::new(3, 1);
    rgb.put_pixel(0, 0, Rgb([255, 0, 0]));
    rgb.put_pixel(1, 0, Rgb([0, 255, 0]));
    rgb.put_pixel(2, 0, Rgb([0, 0, 255]));

    let gray = to_gray_601(&DynamicImage::ImageRgb8(rgb));
    assert_eq!(
        gray.into_raw(),
        vec![76, 150, 29],
        "these are Pillow's values for pure red, green and blue"
    );
}

// ------------------------------------------------------------- orientation

/// A JPEG stored `width` x `height`, black left of `width / 2` and white to
/// the right, saying in its EXIF data that it is to be shown turned:
/// orientation 6 means a quarter turn clockwise.
fn turned_photo(width: u32, height: u32, orientation: u16) -> Vec<u8> {
    let mut rgb = RgbImage::new(width, height);
    for (x, _, pixel) in rgb.enumerate_pixels_mut() {
        *pixel = if x < width / 2 {
            Rgb([0, 0, 0])
        } else {
            Rgb([255, 255, 255])
        };
    }
    let mut jpeg = Vec::new();
    DynamicImage::ImageRgb8(rgb)
        .write_to(
            &mut std::io::Cursor::new(&mut jpeg),
            image::ImageFormat::Jpeg,
        )
        .unwrap();

    // APP1 "Exif": a big-endian TIFF header and one IFD entry, Orientation.
    let mut exif = b"Exif\0\0MM\0\x2a\0\0\0\x08\0\x01\x01\x12\0\x03\0\0\0\x01".to_vec();
    exif.extend_from_slice(&orientation.to_be_bytes());
    exif.extend_from_slice(&[0, 0, 0, 0, 0, 0]);
    let mut segment = vec![0xFF, 0xE1];
    segment.extend_from_slice(&(exif.len() as u16 + 2).to_be_bytes());
    segment.extend_from_slice(&exif);

    jpeg.splice(2..2, segment);
    jpeg
}

/// Mean grey of the top and the bottom half of an image.
fn halves(image: &DynamicImage) -> (f64, f64) {
    let gray = image.to_luma8();
    let mean = |rows: std::ops::Range<u32>| {
        let mut total = 0.0;
        let mut count = 0.0;
        for y in rows {
            for x in 0..gray.width() {
                total += gray.get_pixel(x, y)[0] as f64;
                count += 1.0;
            }
        }
        total / count
    };
    let middle = gray.height() / 2;
    (mean(0..middle), mean(middle..gray.height()))
}

/// Readers show a photo the way its EXIF orientation says, so the converted
/// image has to be turned that way: its tag does not survive conversion.
#[test]
fn a_photo_is_turned_the_way_its_exif_says() {
    let source = turned_photo(60, 40, 6);

    let out =
        decode(&process_image(&source, "phone.jpg", &ImageOptions::default()).unwrap()[0].bytes);

    assert_eq!((out.width(), out.height()), (40, 60), "shown portrait");
    let (top, bottom) = halves(&out);
    assert!(
        top < 64.0 && bottom > 192.0,
        "the stored left half is shown on top: top {top:.0}, bottom {bottom:.0}"
    );
}

/// Light Novel mode turns landscape artwork. A photo stored landscape but
/// shown portrait is not landscape artwork, and is not turned again.
#[test]
fn light_novel_mode_sees_a_photo_in_the_shape_it_is_shown() {
    let source = turned_photo(60, 40, 6);
    let options = ImageOptions {
        light_novel_mode: true,
        ..ImageOptions::default()
    };

    let results = process_image(&source, "phone.jpg", &options).unwrap();
    assert!(!results[0].reshaped, "{}", results[0].details);

    let out = decode(&results[0].bytes);
    assert_eq!((out.width(), out.height()), (40, 60));
    let (top, bottom) = halves(&out);
    assert!(
        top < 64.0 && bottom > 192.0,
        "upright, not turned twice: top {top:.0}, bottom {bottom:.0}"
    );
}

// ------------------------------------------------------------------- size

/// A PNG that says it is `width` x `height` RGBA and holds no pixels: enough
/// for a decoder to judge its size by, with nothing to decode.
fn png_claiming(width: u32, height: u32) -> Vec<u8> {
    fn crc32(bytes: &[u8]) -> u32 {
        let mut crc = !0u32;
        for &byte in bytes {
            crc ^= byte as u32;
            for _ in 0..8 {
                crc = if crc & 1 == 1 {
                    (crc >> 1) ^ 0xEDB8_8320
                } else {
                    crc >> 1
                };
            }
        }
        !crc
    }
    fn chunk(png: &mut Vec<u8>, kind: &[u8; 4], data: &[u8]) {
        png.extend_from_slice(&(data.len() as u32).to_be_bytes());
        let start = png.len();
        png.extend_from_slice(kind);
        png.extend_from_slice(data);
        let crc = crc32(&png[start..]);
        png.extend_from_slice(&crc.to_be_bytes());
    }

    let mut header = Vec::new();
    header.extend_from_slice(&width.to_be_bytes());
    header.extend_from_slice(&height.to_be_bytes());
    header.extend_from_slice(&[8, 6, 0, 0, 0]); // eight-bit RGBA

    let mut png = b"\x89PNG\r\n\x1a\n".to_vec();
    chunk(&mut png, b"IHDR", &header);
    // An empty zlib stream.
    chunk(
        &mut png,
        b"IDAT",
        &[0x78, 0x9c, 0x03, 0x00, 0x00, 0x00, 0x00, 0x01],
    );
    chunk(&mut png, b"IEND", &[]);
    png
}

/// Pillow converts an image of up to about 179 million pixels. The image
/// crate's default allocation limit refused a 12000 x 12000 RGBA one, 144
/// million, which was then left in the book at full size.
#[test]
fn an_image_pillow_would_convert_is_not_refused_for_its_size() {
    let source = png_claiming(12_000, 12_000);

    let error = process_image(&source, "plate.png", &ImageOptions::default())
        .expect_err("it has no pixels to convert")
        .to_string();
    assert!(!error.contains("limit"), "refused for its size: {error}");
}

/// Past Pillow's limit an image is taken for a decompression bomb, and is
/// refused before anything is set aside for its pixels.
#[test]
fn an_image_past_pillows_limit_is_refused_before_it_is_decoded() {
    let source = png_claiming(15_000, 15_000);

    let error = process_image(&source, "bomb.png", &ImageOptions::default())
        .expect_err("too large")
        .to_string();
    assert!(error.contains("limit"), "{error}");
}

/// How the first component of a JPEG is sampled, as its frame header says:
/// `0x22` for luma at twice the chroma's resolution each way, `0x11` for not.
fn luma_sampling(jpeg: &[u8]) -> u8 {
    let frame = jpeg
        .windows(2)
        .position(|marker| marker == [0xFF, 0xC0])
        .expect("a baseline frame");
    jpeg[frame + 11]
}

/// A grey image kept in colour is still grey: its chroma is flat, and
/// halving it costs nothing, where a full-resolution copy of nothing made the
/// file an eighth bigger. The upstream code saved it as greyscale.
#[test]
fn a_grey_image_kept_in_colour_is_not_coded_as_colour() {
    let gradient = GrayImage::from_fn(240, 360, |x, y| Luma([((x + 2 * y) % 256) as u8]));
    let mut source = Vec::new();
    DynamicImage::ImageLuma8(gradient)
        .write_to(
            &mut std::io::Cursor::new(&mut source),
            image::ImageFormat::Png,
        )
        .unwrap();
    let options = ImageOptions {
        grayscale: false,
        ..ImageOptions::default()
    };

    let colour = process_image(&source, "grey.png", &options).unwrap();
    assert_eq!(luma_sampling(&colour[0].bytes), 0x22);

    // An image with colour in it keeps its chroma at full resolution.
    let colourful = process_image(&photo(240, 360), "colour.png", &options).unwrap();
    assert_eq!(luma_sampling(&colourful[0].bytes), 0x11);
}

// ---------------------------------------- Light Novel mode: what is reshaped

fn light_novel(source: &[u8]) -> Vec<epubkit_core::image::ProcessedImage> {
    let options = ImageOptions {
        light_novel_mode: true,
        ..ImageOptions::default()
    };
    process_image(source, "art.png", &options).unwrap()
}

/// The panel never enlarges an image, so one it already shows whole, an
/// ornament or a small figure, is shown no bigger turned: turning it only
/// stands it on end.
#[test]
fn light_novel_mode_leaves_an_image_the_panel_shows_whole_alone() {
    let results = light_novel(&photo(300, 200));

    assert_eq!(results.len(), 1);
    assert!(!results[0].reshaped, "{}", results[0].details);
    let out = decode(&results[0].bytes);
    assert_eq!((out.width(), out.height()), (300, 200));
}

/// Turned, a nearly square image is shown hardly bigger, which is not worth
/// turning the reader for.
#[test]
fn light_novel_mode_leaves_a_nearly_square_image_alone() {
    let results = light_novel(&photo(1300, 1200));

    assert_eq!(results.len(), 1);
    assert!(!results[0].reshaped, "{}", results[0].details);
}

/// An image far wider than tall is a rule or a banner, not a spread of two
/// pages, and its halves would be nonsense.
#[test]
fn light_novel_mode_does_not_split_a_banner() {
    let results = light_novel(&photo(1500, 400));

    assert_eq!(results.len(), 1);
    assert!(!results[0].reshaped, "{}", results[0].details);
    let out = decode(&results[0].bytes);
    assert!(
        out.width() > out.height() * 3,
        "{}x{}",
        out.width(),
        out.height()
    );
}

/// Fine regular patterns, screentone or hatching, have to average out to an
/// even grey when shrunk. Averaging blocks of pixels first, to save time, let
/// stripes five pixels apart beat against the blocks into broad bands.
#[test]
fn fine_stripes_shrink_to_an_even_grey() {
    let stripes = GrayImage::from_fn(2001, 61, |x, _| Luma([if x % 5 < 2 { 0 } else { 255 }]));
    let mut source = Vec::new();
    DynamicImage::ImageLuma8(stripes)
        .write_to(
            &mut std::io::Cursor::new(&mut source),
            image::ImageFormat::Png,
        )
        .unwrap();
    let options = ImageOptions {
        contrast_boost: false,
        eink_quantize: false,
        quality: 95,
        ..ImageOptions::default()
    };

    let out = decode(&process_image(&source, "stripes.png", &options).unwrap()[0].bytes).to_luma8();

    let (width, height) = out.dimensions();
    let columns: Vec<f64> = (4..width - 4)
        .map(|x| {
            (2..height - 2)
                .map(|y| out.get_pixel(x, y)[0] as f64)
                .sum::<f64>()
                / (height - 4) as f64
        })
        .collect();
    let lightest = columns.iter().cloned().fold(f64::MIN, f64::max);
    let darkest = columns.iter().cloned().fold(f64::MAX, f64::min);
    assert!(
        lightest - darkest < 8.0,
        "{width}x{height}: columns from {darkest:.0} to {lightest:.0}"
    );
}

/// What converting an image will hold is reckoned before its file is read:
/// the file itself, and the image decoded at its own depth, which for sixteen
/// bits a channel with alpha is eight bytes a pixel, held twice.
#[test]
fn the_memory_an_image_needs_counts_its_file_and_its_depth() {
    let deep = image::ImageBuffer::<image::Rgba<u16>, Vec<u16>>::from_pixel(
        64,
        48,
        image::Rgba([1, 2, 3, 4]),
    );
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("deep.png");
    DynamicImage::ImageRgba16(deep).save(&path).unwrap();
    let file = std::fs::metadata(&path).unwrap().len();

    let needed = epubkit_core::image::memory_needed(&path);

    assert!(needed >= file + 64 * 48 * 16, "{needed}");
}

/// A thumbnail averages blocks of pixels, and the block sum of a 16-bit image
/// overflowed: a white 257 x 257 one shrunk to one pixel came out black, and
/// a debug build panicked.
#[test]
fn a_deep_image_shrunk_far_stays_as_light_as_it_is() {
    let white = image::ImageBuffer::<Luma<u16>, Vec<u16>>::from_pixel(257, 257, Luma([65535]));
    let mut png = Vec::new();
    DynamicImage::ImageLuma16(white)
        .write_to(&mut std::io::Cursor::new(&mut png), image::ImageFormat::Png)
        .unwrap();

    let budget = epubkit_core::memory::MemoryBudget::new(1 << 30);
    let jpeg = epubkit_core::image::thumbnail(&png, 1, 1, &budget).unwrap();

    let pixel = decode(&jpeg).to_luma8().get_pixel(0, 0)[0];
    assert!(pixel > 250, "white came out {pixel}");
}
