//! Pixel operations checked against Pillow's own output.
//!
//! The fixtures in `tests/fixtures/` were generated by running Pillow directly
//! (see `PORTING.md`). They exist so the reproductions of `convert("L")`,
//! `ImageOps.autocontrast` and `ImageEnhance.Contrast` cannot drift without a
//! test noticing.

use std::collections::BTreeSet;

use epubkit_core::image::{
    adjust_contrast, autocontrast, device, floyd_steinberg, luma_601, process_image,
    should_process, to_gray_601, ImageOptions, MAX_IMAGE_DIMENSION, SSD1677_LEVELS, X3, X4,
};
use image::{DynamicImage, GrayImage, Luma, Rgb, RgbImage};

fn fixture(name: &str) -> String {
    std::fs::read_to_string(format!(
        "{}/tests/fixtures/{name}",
        env!("CARGO_MANIFEST_DIR")
    ))
    .unwrap_or_else(|e| panic!("missing fixture {name}: {e}"))
}

/// Read a two-line fixture: input values, then Pillow's expected output.
fn pixel_fixture(name: &str) -> (Vec<u8>, Vec<u8>) {
    let text = fixture(name);
    let mut lines = text.lines();
    let parse = |line: &str| -> Vec<u8> {
        line.split_whitespace()
            .map(|v| v.parse().expect("fixture value"))
            .collect()
    };
    let input = parse(lines.next().expect("input line"));
    let expected = parse(lines.next().expect("expected line"));
    assert_eq!(input.len(), expected.len());
    (input, expected)
}

fn row(values: &[u8]) -> GrayImage {
    GrayImage::from_raw(values.len() as u32, 1, values.to_vec()).expect("row image")
}

#[test]
fn grayscale_matches_pillow() {
    let mut checked = 0;
    for line in fixture("luma601.txt").lines() {
        let v: Vec<u32> = line
            .split_whitespace()
            .map(|n| n.parse().unwrap())
            .collect();
        let (r, g, b, expected) = (v[0] as u8, v[1] as u8, v[2] as u8, v[3] as u8);
        assert_eq!(
            luma_601(r, g, b),
            expected,
            "luma_601({r},{g},{b}) disagrees with Pillow"
        );
        checked += 1;
    }
    assert!(checked > 1000, "fixture looks truncated: {checked} samples");
}

/// The whole reason for writing the coefficients out by hand: the Rec. 709
/// values most crates default to give visibly different greys.
#[test]
fn grayscale_is_not_rec_709() {
    // Pure green is where the two standards disagree most.
    assert_eq!(luma_601(0, 255, 0), 150);
    let rec709 = (255u32 * 7152 / 10000) as u8;
    assert_ne!(luma_601(0, 255, 0), rec709);
}

#[test]
fn autocontrast_matches_pillow() {
    for name in [
        "autocontrast_full.txt",
        "autocontrast_narrow.txt",
        "autocontrast_dark.txt",
        "autocontrast_flat.txt",
    ] {
        let (input, expected) = pixel_fixture(name);
        let mut gray = row(&input);
        autocontrast(&mut gray, 1);
        assert_eq!(gray.into_raw(), expected, "{name} disagrees with Pillow");
    }
}

#[test]
fn contrast_matches_pillow() {
    for (name, factor) in [
        ("contrast_15.txt", 1.5),
        ("contrast_20.txt", 2.0),
        ("contrast_05.txt", 0.5),
    ] {
        let (input, expected) = pixel_fixture(name);
        let mut gray = row(&input);
        adjust_contrast(&mut gray, factor);
        assert_eq!(gray.into_raw(), expected, "{name} disagrees with Pillow");
    }
}

/// Contrast pivots about the image's own mean, not mid-grey. On a dark image
/// the two give very different answers, and getting it wrong would blow out
/// every night scene in every book.
#[test]
fn contrast_pivots_on_the_image_mean() {
    let dark = vec![40u8; 100];
    let mut gray = row(&dark);
    adjust_contrast(&mut gray, 2.0);

    // Mean is 40, so every pixel is already at the pivot and cannot move.
    assert!(
        gray.pixels().all(|p| p[0] == 40),
        "a flat image should be unchanged by a contrast adjustment"
    );

    // Pivoting on 128 would have pushed these to 0.
    let naive = (128.0 + 2.0 * (40.0 - 128.0)) as i32;
    assert!(naive < 0, "sanity: the naive pivot would clamp to black");
}

#[test]
fn dithering_emits_only_device_levels() {
    // A smooth ramp is the hardest case: every intermediate value has to be
    // expressed as a mix of the four available ones.
    let ramp: Vec<u8> = (0..=255u8).collect();
    let mut gray = GrayImage::from_raw(16, 16, ramp).unwrap();

    floyd_steinberg(&mut gray, SSD1677_LEVELS);

    let seen: BTreeSet<u8> = gray.pixels().map(|p| p[0]).collect();
    let allowed: BTreeSet<u8> = SSD1677_LEVELS.iter().copied().collect();
    assert!(
        seen.is_subset(&allowed),
        "output contains values outside the palette: {seen:?}"
    );
}

/// Error diffusion's defining property: it trades spatial accuracy for tonal
/// accuracy, so the average brightness of a region survives quantization.
#[test]
fn dithering_preserves_average_brightness() {
    for level in [30u8, 64, 100, 128, 190, 220] {
        let mut gray = GrayImage::from_pixel(64, 64, Luma([level]));
        floyd_steinberg(&mut gray, SSD1677_LEVELS);

        let mean: f64 =
            gray.pixels().map(|p| p[0] as f64).sum::<f64>() / gray.pixels().len() as f64;
        assert!(
            (mean - level as f64).abs() < 6.0,
            "flat {level} dithered to mean {mean:.1}, too far off"
        );
    }
}

/// A mid-tone that is not itself a palette level has to be rendered as a mix,
/// not snapped to the nearest level across the whole region.
#[test]
fn dithering_actually_diffuses() {
    let mut gray = GrayImage::from_pixel(32, 32, Luma([128]));
    floyd_steinberg(&mut gray, SSD1677_LEVELS);

    let seen: BTreeSet<u8> = gray.pixels().map(|p| p[0]).collect();
    assert!(
        seen.len() >= 2,
        "a flat mid-tone should dither to a mix, got {seen:?}"
    );
}

#[test]
fn dithering_a_flat_palette_value_is_a_no_op() {
    for &level in SSD1677_LEVELS {
        let mut gray = GrayImage::from_pixel(8, 8, Luma([level]));
        floyd_steinberg(&mut gray, SSD1677_LEVELS);
        assert!(
            gray.pixels().all(|p| p[0] == level),
            "level {level} should survive untouched"
        );
    }
}

// ------------------------------------------------------------ whole pipeline

fn photo(width: u32, height: u32) -> Vec<u8> {
    // A gradient with a hard edge: exercises both smooth tone and detail.
    let mut rgb = RgbImage::new(width, height);
    for (x, y, pixel) in rgb.enumerate_pixels_mut() {
        let ramp = ((x * 255) / width.max(1)) as u8;
        let band = if (y / 8) % 2 == 0 { 40 } else { 0 };
        *pixel = Rgb([ramp.saturating_add(band), ramp, 255 - ramp]);
    }

    let mut out = Vec::new();
    DynamicImage::ImageRgb8(rgb)
        .write_to(&mut std::io::Cursor::new(&mut out), image::ImageFormat::Png)
        .unwrap();
    out
}

fn decode(bytes: &[u8]) -> DynamicImage {
    image::load_from_memory(bytes).expect("output should decode")
}

#[test]
fn processing_fits_the_device_box() {
    let source = photo(1600, 2400);
    let results = process_image(&source, "plate.png", &ImageOptions::for_device(X4)).unwrap();

    assert_eq!(results.len(), 1);
    let out = decode(&results[0].bytes);
    assert!(out.width() <= X4.width, "width {} > 480", out.width());
    assert!(out.height() <= X4.height, "height {} > 800", out.height());
    assert_eq!(results[0].filename, "plate.jpg");
}

#[test]
fn the_x3_profile_uses_its_own_box() {
    let source = photo(1600, 2400);
    let results = process_image(&source, "plate.png", &ImageOptions::for_device(X3)).unwrap();
    let out = decode(&results[0].bytes);

    assert!(out.width() <= X3.width);
    assert!(out.height() <= X3.height);
    assert_eq!(device("x3").unwrap().width, 528);
}

#[test]
fn small_images_are_never_enlarged() {
    let source = photo(100, 120);
    let results = process_image(&source, "small.png", &ImageOptions::default()).unwrap();
    let out = decode(&results[0].bytes);

    assert_eq!((out.width(), out.height()), (100, 120));
}

/// The Xteink spec caps images at 1024 in either direction, regardless of the
/// panel's own size.
#[test]
fn the_hard_dimension_ceiling_is_enforced() {
    let source = photo(4000, 200);
    let options = ImageOptions {
        max_width: 100_000,
        max_height: 100_000,
        ..ImageOptions::default()
    };

    let out = decode(&process_image(&source, "wide.png", &options).unwrap()[0].bytes);
    assert!(out.width() <= MAX_IMAGE_DIMENSION);
    assert!(out.height() <= MAX_IMAGE_DIMENSION);
}

#[test]
fn output_is_baseline_jpeg() {
    let source = photo(400, 600);
    let results = process_image(&source, "plate.png", &ImageOptions::default()).unwrap();
    let bytes = &results[0].bytes;

    assert_eq!(&bytes[0..2], &[0xFF, 0xD8], "not a JPEG");
    // SOF2 marks a progressive frame, which many e-ink readers cannot decode.
    assert!(
        !bytes.windows(2).any(|w| w == [0xFF, 0xC2]),
        "progressive JPEG emitted"
    );
    assert!(
        bytes.windows(2).any(|w| w == [0xFF, 0xC0]),
        "no baseline frame header found"
    );
}

/// Tone survives the whole pipeline. Quantizing to four levels and then
/// encoding to a lossy format should still leave a flat grey reading as that
/// grey overall — which is the property error diffusion exists to provide.
#[test]
fn overall_brightness_survives_the_pipeline() {
    for level in [64u8, 128, 190] {
        let mut rgb = RgbImage::new(128, 128);
        for pixel in rgb.pixels_mut() {
            *pixel = Rgb([level, level, level]);
        }
        let mut source = Vec::new();
        DynamicImage::ImageRgb8(rgb)
            .write_to(
                &mut std::io::Cursor::new(&mut source),
                image::ImageFormat::Png,
            )
            .unwrap();

        let out =
            decode(&process_image(&source, "flat.png", &ImageOptions::default()).unwrap()[0].bytes)
                .to_luma8();
        let mean: f64 = out.pixels().map(|p| p[0] as f64).sum::<f64>() / out.pixels().len() as f64;

        assert!(
            (mean - level as f64).abs() < 8.0,
            "flat {level} came out of the pipeline at {mean:.1}"
        );
    }
}

/// A solid white image must come back solid white. This is the regression
/// guard for the encoder settings, and it earned its keep: it caught
/// `jpeg-encoder`'s optimized-table mode splitting the interleaved scan into
/// three single-component scans, which is legal baseline JPEG but which
/// several decoders — this crate's included — turn into noise. Optimized
/// tables now come from rewriting the finished file instead, which leaves the
/// scan structure alone. See `core::jpeg`.
#[test]
fn a_solid_image_round_trips_through_our_own_decoder() {
    let mut rgb = RgbImage::new(96, 96);
    for pixel in rgb.pixels_mut() {
        *pixel = Rgb([255, 255, 255]);
    }
    let mut source = Vec::new();
    DynamicImage::ImageRgb8(rgb)
        .write_to(
            &mut std::io::Cursor::new(&mut source),
            image::ImageFormat::Png,
        )
        .unwrap();

    let options = ImageOptions {
        contrast_boost: false,
        ..ImageOptions::default()
    };
    let out = decode(&process_image(&source, "white.png", &options).unwrap()[0].bytes).to_luma8();

    let min = out.pixels().map(|p| p[0]).min().unwrap();
    assert!(min > 240, "solid white decoded with pixels down to {min}");
}

#[test]
fn transparency_is_flattened_onto_white() {
    let mut rgba = image::RgbaImage::new(40, 40);
    for pixel in rgba.pixels_mut() {
        *pixel = image::Rgba([0, 0, 0, 0]); // fully transparent black
    }
    let mut source = Vec::new();
    DynamicImage::ImageRgba8(rgba)
        .write_to(
            &mut std::io::Cursor::new(&mut source),
            image::ImageFormat::Png,
        )
        .unwrap();

    let options = ImageOptions {
        contrast_boost: false,
        ..ImageOptions::default()
    };
    let out = decode(&process_image(&source, "clear.png", &options).unwrap()[0].bytes).to_luma8();

    let mean: f64 = out.pixels().map(|p| p[0] as f64).sum::<f64>() / out.pixels().len() as f64;
    assert!(
        mean > 200.0,
        "transparent pixels should have flattened to white, mean was {mean:.1}"
    );
}

#[test]
fn light_novel_mode_splits_a_double_page_spread() {
    let source = photo(2000, 800); // aspect 2.5, well past the spread threshold
    let options = ImageOptions {
        light_novel_mode: true,
        ..ImageOptions::default()
    };

    let results = process_image(&source, "spread.png", &options).unwrap();

    assert_eq!(results.len(), 2, "a spread should become two pages");
    assert_eq!(results[0].filename, "spread_part1.jpg");
    assert_eq!(results[1].filename, "spread_part2.jpg");
    // Only the first result carries the source size, so a report cannot count
    // the same input twice.
    assert!(results[0].original_size > 0);
    assert_eq!(results[1].original_size, 0);
}

#[test]
fn light_novel_mode_rotates_a_single_landscape_image() {
    let source = photo(800, 600); // aspect 1.33, below the spread threshold
    let options = ImageOptions {
        light_novel_mode: true,
        ..ImageOptions::default()
    };

    let results = process_image(&source, "plate.png", &options).unwrap();
    assert_eq!(results.len(), 1);

    let out = decode(&results[0].bytes);
    assert!(
        out.height() > out.width(),
        "a rotated landscape image should end up portrait, got {}x{}",
        out.width(),
        out.height()
    );
}

#[test]
fn light_novel_mode_leaves_portrait_images_alone() {
    let source = photo(600, 900);
    let options = ImageOptions {
        light_novel_mode: true,
        ..ImageOptions::default()
    };

    let results = process_image(&source, "portrait.png", &options).unwrap();
    assert_eq!(results.len(), 1);
    assert_eq!(results[0].filename, "portrait.jpg");
}

#[test]
fn every_output_is_renamed_to_jpg() {
    for name in ["a.png", "b.GIF", "c.webp", "d.bmp", "e.jpeg"] {
        let source = photo(60, 80);
        let results = process_image(&source, name, &ImageOptions::default()).unwrap();
        assert!(
            results[0].filename.ends_with(".jpg"),
            "{name} produced {}",
            results[0].filename
        );
    }
}

#[test]
fn supported_extensions_are_recognized_case_insensitively() {
    for name in [
        "a.png", "b.JPG", "c.Jpeg", "d.webp", "e.TIFF", "f.bmp", "g.gif",
    ] {
        assert!(should_process(name), "{name} should be processable");
    }
    for name in ["a.svg", "b.xhtml", "c.css", "d.otf", "e"] {
        assert!(!should_process(name), "{name} should be skipped");
    }
}

#[test]
fn corrupt_input_is_reported_not_panicked_on() {
    let garbage = b"this is not an image at all";
    assert!(process_image(garbage, "broken.png", &ImageOptions::default()).is_err());
}

#[test]
fn grayscale_can_be_turned_off() {
    let source = photo(200, 300);
    let options = ImageOptions {
        grayscale: false,
        eink_quantize: false,
        contrast_boost: false,
        ..ImageOptions::default()
    };

    let out = decode(&process_image(&source, "colour.png", &options).unwrap()[0].bytes).to_rgb8();
    let has_colour = out.pixels().any(|p| p[0] != p[1] || p[1] != p[2]);
    assert!(has_colour, "colour should have survived with grayscale off");
}

#[test]
fn details_describe_what_happened() {
    let source = photo(1600, 2400);
    let results = process_image(&source, "plate.png", &ImageOptions::default()).unwrap();
    let details = &results[0].details;

    assert!(details.contains("PNG→JPEG"), "{details}");
    assert!(details.contains("resized"), "{details}");
    assert!(details.contains("4-level grayscale"), "{details}");
    assert!(details.contains("contrast 1.5x"), "{details}");
}

#[test]
fn gray_conversion_goes_through_601() {
    let mut rgb = RgbImage::new(3, 1);
    rgb.put_pixel(0, 0, Rgb([255, 0, 0]));
    rgb.put_pixel(1, 0, Rgb([0, 255, 0]));
    rgb.put_pixel(2, 0, Rgb([0, 0, 255]));

    let gray = to_gray_601(&DynamicImage::ImageRgb8(rgb));
    assert_eq!(
        gray.into_raw(),
        vec![76, 150, 29],
        "these are Pillow's values for pure red, green and blue"
    );
}
